# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('person_id', models.CharField(max_length=128)),
                ('face_id', models.CharField(max_length=128)),
                ('weight', models.FloatField()),
                ('last_tagged', models.TimeField()),
                ('group', models.CharField(max_length=128)),
            ],
        ),
    ]
